{% set version = "4.7.0" %}

package:
  name: humanize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanize/humanize-{{ version }}.tar.gz
  sha256: 7ca0e43e870981fa684acb5b062deb307218193bca1a01f2b2676479df849b3a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.7
    - importlib-metadata

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - humanize

about:
  home: https://github.com/python-humanize/humanize
  license: MIT
  license_file: LICENCE
  summary: Python humanize utilities

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ocefpaf
