{% set version = "4.5.0" %}

package:
  name: humanize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanize/humanize-{{ version }}.tar.gz
  sha256: d6ed00ed4dc59a66df71012e3d69cf655d7d21b02112d435871998969e8aedc8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - importlib-metadata

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - humanize

about:
  home: https://github.com/python-humanize/humanize
  license: MIT
  license_file: LICENCE
  summary: Python humanize utilities

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ocefpaf
