{% set name = "humanize" %}
{% set version = "4.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/humanize-{{ version }}.tar.gz
  sha256: e66f36020a2d5a974c504bd2555cf770621dbdbb6d82f94a6857c0b1ea2608be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  number: 0

requirements:
  host:
    - python >=3.9
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=3.9

test:
  imports:
    - humanize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-humanize/humanize
  license: MIT
  license_file: LICENCE
  summary: Python humanize utilities

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ocefpaf
