{% set version = "1.0.0" %}
package:
  name: humanize
  version: {{ version }}

source:
  fn: humanize-{{ version }}.tar.gz
  url: https://github.com/jmoiron/humanize/archive/{{ version }}.tar.gz
  sha256: 0b50fc223d3439f98fe8df7e9ccdc1b0b1a7485bcd944625b2f727ead6566033

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - humanize

about:
  home: https://github.com/jmoiron/humanize
  license: MIT
  license_file: LICENCE
  summary: 'Python humanize utilities.'

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ocefpaf
