{% set version = "2.6.0" %}

package:
  name: humanize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/humanize/humanize-{{ version }}.tar.gz
  sha256: 8ee358ea6c23de896b9d1925ebe6a8504bb2ba7e98d5ccf4d07ab7f3b28f3819

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - humanize

about:
  home: https://github.com/jmoiron/humanize
  license: MIT
  license_file: LICENCE
  summary: Python humanize utilities

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ocefpaf
