travis:
  secure:
    BINSTAR_TOKEN: ts2IqGs6r9BObU2z4Gq6OYUHFhmKiVlEH4XMTBhnlgvbsiB5y7raA63P7Jbk8TmdE9VPxgEPBFhOL4ZOW6yGL73wZS8utazN++UIT7cU7Iqur1eswbrfARAKTztHDX5UQcX6TrU0jguqFJTE411k0fmX1KufQYsVlFD2Wg7ur4chZfwQ0jEVjjWUIpEfk543a9oY1K7xqOlL8jnDaRmVY8YqZ3A5K9RcBabV0MvubOceDgzVhGfuBKgHOZOvYg9ASJmoQ49mGAfJsPsiHXApUVizmdvVFdKzaQX//Y8JfcZDEDtpmjHvtrsZ4tV1bqetkIFcAQkbKgMiVydgU/jSoaBLkNUGKT+tb+D+DHiEsWQcpnAuP5FGbA7VeuGBzGDG3YRl0iZpwvaESyLNLuXqEvYMXcB119IdeieisD7V6CZ01RMlet/u1bAU/5DtSOXYXcIHW3cWfZkFXepJqS8Uqi865F5Rer+VHXFrhtxqeIFKuMzqNzf1YbngjLfeO4vNKLOga12f2qPiqeHUd5CQpggPM9twPx97SV8FsiADODsupRSV46okUhdHoIA4VXZBVLFnQXAAB0bRCSfmm57CvvCnRbMHDoPs8DNRrHzCsVzYqm+EG8JPRpO/mSyTw9HJ4c09IKPeIYqwxPYqEPqendAvbsgHwXZ7LMrnSgGKG7U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
